logFilters:
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
