name: Publish dev
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  npm-publish:
    name: npm publish
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@discordjs/brokers'
            folder: 'brokers'
          - package: '@discordjs/builders'
            folder: 'builders'
          - package: '@discordjs/collection'
            folder: 'collection'
          - package: '@discordjs/core'
            folder: 'core'
          - package: '@discordjs/formatters'
            folder: 'formatters'
          - package: 'discord.js'
            folder: 'discord.js'
          - package: '@discordjs/next'
            folder: 'next'
          - package: '@discordjs/proxy'
            folder: 'proxy'
          - package: '@discordjs/rest'
            folder: 'rest'
          - package: '@discordjs/util'
            folder: 'util'
          - package: '@discordjs/voice'
            folder: 'voice'
          - package: '@discordjs/ws'
            folder: 'ws'
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    if: github.repository_owner == 'discordjs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmCache

      - name: Build dependencies
        run: pnpm run build

      - name: Publish package
        run: |
          pnpm --filter=${{ matrix.package }} run release --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)"
          pnpm --filter=${{ matrix.package }} publish --no-git-checks --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Deprecate prior development releases
        run: pnpm exec npm-deprecate --name "*dev*" --message "This version is deprecated. Please use a newer version." --package ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
